<!DOCTYPE html>
<html lang="en">
<head>
    <title>4K Beast - The Ultimate 4K Experience</title>
    <link rel="stylesheet" href="style.css">
    <meta charset="UTF-8">
    <meta name="description" content="Explore 4K Ultra HD TVs, with stunning clarity and immersive features.">
    <meta name="keywords" content="4K TV, Ultra HD, Smart TV, LED TV, 4K Beast">
    <meta name="author" content="Taniksha Dabral">
</head>
<body>

<header>
    <nav class="NavBar">
        <a href="index.html" class="logo">
            <img src="images/4Klogo.png" alt="4K Beast Logo">
        </a>
        <ul>
            <li><a href="index.php">Home</a></li>
            <li><a href="product.php">Products</a></li>
            <li><a href="enquire.php">Enquire</a></li>
            <li><a href="about.php">About</a></li>
            <li><a href="payment.php">Payement</a></li>
            <li><a href="enhancement.php">Enhancements</a></li>
        </ul>
    </nav>
</header>